create table post(
    id       int8 generated by default as identity,
    filename varchar(255),
    tag      varchar(255),
    text     varchar(2048),
    user_id  int8,
    primary key (id)
);

create table roles(
    id   int8 generated by default as identity,
    name varchar(50) not null,
    primary key (id)
);

create table users(
    id       int8 generated by default as identity,
    password varchar(80) not null,
    username varchar(30) not null,
    primary key (id)
);

create table users_roles
(
    user_id int8 not null,
    role_id int8 not null
);

alter table if exists post
    add constraint post_user_fk foreign key (user_id) references users;

alter table if exists users_roles
    add constraint user_role_fk foreign key (role_id) references roles;

alter table if exists users_roles
    add constraint role_user_fk foreign key (user_id) references users;

insert into roles values (1,'ROLE_ADMIN');
insert into roles values (2, 'ROLE_USER');
insert into users values (1,'$2a$10$L7sFU8rFFSFSYaEYjY52gO0CF0fR3X71nChF9JnNu4KuuUcmLmgV2','oleg');
insert into users_roles values (1,1);